[project]
name = "yt_mcp"
version = "0.1.0"
description = "MCP server exposing a YouTube comments fetch tool"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
  "mcp[cli]>=0.1.0",
  "httpx>=0.27",
  "python-dotenv>=1.0",
]

[tool.uv]
dev-dependencies = []
